services:
  - type: web
    name: alish-portfolio-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PORT
        value: 5000
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REFRESH_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
